<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <h1>Fundamentos Javascript</h1>


    <script>
try {
    console.log("en el try se agrega el codigo a evaluar")
    noExite
    console.log("Segundo mensaje en el try")
} catch (error) {
    console.log("Catch,captura cualquier error surgido o lanzado en el try")
    console.log(error)
}finally{
    console.log("El bloque finally se ejecutará siempre al ginal de un bloque try-catch")
}


try {
    let numero = "dasdas"
    // isNaN si es una funcion que tu le pasas un numero si no es un numero te va a regresar verdadero
    if(isNaN(numero)){
        throw new Error("El caractér introducido no es un Número")
    }
    console.log(numero*numero)
} catch (error) {
    console.log(`Se produjo el siguiente error: ${error}`)
}
</script>
    



</body>

</html>